# Generated by Django 5.2.7 on 2025-10-16 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('internpage', '0005_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companypost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='internpage.jobpost')),
            ],
        ),
    ]
