# Generated by Django 5.2.7 on 2025-10-16 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_user_industry_type_user_location_user_phone_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_no',
        ),
    ]
