# Generated by Django 5.2.7 on 2025-10-12 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='date_posted',
            field=models.DateField(blank=True, null=True),
        ),
    ]
