# Generated by Django 5.2.7 on 2025-10-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internpage', '0002_jobpost_date_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='experience',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='responsiablity',
            field=models.TextField(null=True),
        ),
    ]
