# Generated by Django 5.2.7 on 2025-10-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internpage', '0003_jobpost_experience_jobpost_responsiablity'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='reciver_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
