# Generated by Django 5.2.7 on 2025-10-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internpage', '0006_candidate_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate_profile',
            name='projects',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='candidate_profile',
            name='summary',
            field=models.TextField(null=True),
        ),
    ]
